
{% set version = environ.get('GIT_DESCRIBE_TAG').lstrip('v') %}
{% set number = GIT_DESCRIBE_NUMBER %}

package:
  name: collie-pkg
  version: {{ version }}

build:
  number: {{ number }}

about:
  home: https://github.com/gottingen/collie
  license: Apache License 2
  license_family: APACHE
  license_file: LICENSE
  summary: header only library for EA Group

source:
  git_url: ../

outputs:
  - name: collie
    script: bld.sh   # [not win]
    script: bld.bat  # [win]
    build:
      string: "h{{ GIT_DESCRIBE_HASH }}_{{ number }}"
      run_exports:
        - {{ pin_compatible('collie', exact=True) }}
    requirements:
      build:
        - {{ compiler('cxx') }}
        - sysroot_linux-64 # [linux]
        - cmake
        - make

      host:
      run:
    test:
      commands:
        - test -f $PREFIX/include/version.h              # [linux]
      #  - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
      #  - conda inspect objects -p $PREFIX $PKG_NAME   # [osx]
