
include(carbin_print)
include(carbin_platform)

set(CARBIN_GENERATOR "STGZ;RPM")
set(CPACK_GENERATOR "STGZ;RPM")
carbin_print("on platform ${PRETTY_NAME} package type ${CARBIN_GENERATOR}")

set(CPACK_PACKAGING_INSTALL_PREFIX ${CARBIN_PACKAGING_INSTALL_PREFIX})
set(CPACK_PACKAGE_VENDOR "${CARBIN_PACKAGE_VENDOR}")
set(CPACK_PACKAGE_NAME "${CARBIN_PACKAGE_NAME}")
set(CPACK_PACKAGE_VERSION "${CARBIN_PACKAGE_VERSION}")
set(CPACK_PACKAGE_DESCRIPTION
        "${CARBIN_PACKAGE_DESCRIPTION}"
)
set(CPACK_PACKAGE_MAINTAINER "${CARBIN_PACKAGE_MAINTAINER}")
set(CPACK_PACKAGE_CONTACT "${CARBIN_PACKAGE_CONTACT}")
set(CPACK_PACKAGE_HOMEPAGE_URL "${CARBIN_PACKAGE_HOMEPAGE_URL}")
set(CPACK_PACKAGE_FILE_NAME "${CARBIN_PACKAGE_FILE_NAME}")
set(CPACK_PACKAGE_DIRECTORY ${CARBIN_PACKAGE_DIRECTORY})

set(CPACK_RPM_PACKAGE_DEBUG 1)
set(CPACK_RPM_RUNTIME_DEBUGINFO_PACKAGE ON)
set(CPACK_RPM_PACKAGE_RELOCATABLE ON)
SET(CPACK_RPM_PRE_INSTALL_SCRIPT_FILE "${PROJECT_SOURCE_DIR}/carbin_cmake/package/preinst")
SET(CPACK_RPM_POST_INSTALL_SCRIPT_FILE "${PROJECT_SOURCE_DIR}/carbin_cmake/package/postinst")
SET(CPACK_RPM_PRE_UNINSTALL_SCRIPT_FILE "${PROJECT_SOURCE_DIR}/carbin_cmake/package/prerm")
SET(CPACK_RPM_POST_UNINSTALL_SCRIPT_FILE "${PROJECT_SOURCE_DIR}/carbin_cmake/package/postrm")
include(CPack)

